dataset_name: 'scannet'
camera_params:
  image_height: 480
  image_width: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.500000
  cy: 239.500000
  png_depth_scale: 1000.0 #for depth image in png format
